# Generated by Django 3.0.6 on 2020-06-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, upload_to='presenterx/images/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
