# Generated by Django 3.0.6 on 2020-06-22 18:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0002_auto_20200619_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=tinymce.models.HTMLField(max_length=500),
        ),
    ]
