# Generated by Django 3.0.6 on 2020-06-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0003_auto_20200622_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Not specified', max_length=30)),
                ('time', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('link', models.URLField(blank=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presenterz.Lecture')),
            ],
        ),
    ]
