# Generated by Django 3.0.6 on 2020-06-23 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0005_auto_20200623_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 18, 44, 45, 49760, tzinfo=utc)),
        ),
    ]
