# Generated by Django 3.0.6 on 2020-06-25 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0006_auto_20200623_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='length',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 7, 2, 778897, tzinfo=utc)),
        ),
    ]
