# Generated by Django 3.0.6 on 2020-06-27 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0008_auto_20200627_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parrticipation',
            old_name='signup_date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 9, 35, 18, 998431, tzinfo=utc)),
        ),
    ]
