# Generated by Django 3.0.6 on 2020-06-27 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenterz', '0009_auto_20200627_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parrticipation',
            new_name='Participation',
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 9, 40, 40, 128701, tzinfo=utc)),
        ),
    ]
