# Generated by Django 3.0.6 on 2020-06-27 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0010_auto_20200627_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 9, 44, 21, 657129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 9, 44, 21, 656092, tzinfo=utc)),
        ),
    ]
