# Generated by Django 3.0.6 on 2020-06-27 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0011_auto_20200627_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 9, 45, 16, 874820, tzinfo=utc)),
        ),
    ]
