# Generated by Django 3.0.6 on 2020-06-27 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenterz', '0013_auto_20200627_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'session')},
        ),
    ]
