# Generated by Django 3.0.6 on 2020-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0014_auto_20200627_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
