# Generated by Django 3.0.6 on 2020-06-27 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0016_auto_20200627_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
