# Generated by Django 3.0.6 on 2020-06-27 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presenterz', '0017_auto_20200627_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
