# Generated by Django 3.0.6 on 2020-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200708_2240'),
        ('matazim', '0002_auto_20200709_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='members',
            field=models.ManyToManyField(to='main.Profile'),
        ),
    ]
