# Generated by Django 3.0.6 on 2020-07-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200708_2240'),
        ('matazim', '0003_program_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='members',
            field=models.ManyToManyField(blank=True, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='members',
            field=models.ManyToManyField(blank=True, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='program',
            name='members',
            field=models.ManyToManyField(blank=True, to='main.Profile'),
        ),
    ]
