# Generated by Django 3.0.6 on 2020-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matazim', '0004_auto_20200709_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='programs',
            field=models.ManyToManyField(blank=True, to='matazim.Program'),
        ),
    ]
