# Generated by Django 3.0.6 on 2020-07-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matazim', '0005_auto_20200709_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facilitator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='matazim.Facilitator'),
            preserve_default=False,
        ),
    ]
